import { EOS_Settlement, TerminationReasonKuwait } from '../../types';


export const initialSavedCases: EOS_Settlement[] = [
  {
    id: 'EOS-1029',
    settlementNumber: 'SET-2026-1029',
    employeeId: '295111245678',
    employeeName: 'أحمد جاسم الشمري',
    department: 'شؤون المبيعات والتوريد',
    settlementDate: '2026-05-25',
    lastWorkingDay: '2026-05-25',
    joiningDate: '2018-02-10',
    terminationReason: TerminationReasonKuwait.DISMISSAL_WITH_NOTICE,
    status: 'PendingReview',
    basicSalary: 850,
    allowances: 150,
    grossSalary: 1000,
    serviceYears: 8,
    serviceMonths: 3,
    serviceDays: 15,
    indemnityAmount: 6174.520,
    leaveBalanceAmount: 1730.760,
    accruedSalaryAmount: 0,
    noticePeriodAmount: 0,
    otherBonuses: 0,
    loansDeduction: 400,
    absenceDeduction: 0,
    otherDeductions: 0,
    netPayable: 7505.280,
    legalArticles: ['المادة 51', 'المادة 70'],
    notes: 'بانتظار موافقة المدير العام واعتماد الإدارة التنفيذية لإطلاق الصرف البنكي النهائي، تم استبقاء خصم 400 دينار كويتي عهدة قروض معلقة لصالح خزانة المنظومة.',
    preparedBy: 'شؤون الموظفين - هادي العنزي',
    nationality: 'كويتي',
    jobTitle: 'مهندس أول جودة وتوريد',
    leaveBalanceDays: 45,
    absenceDays: 0,
    socialInsuranceDeduction: 0,
    unpaidLeaveDays: 0,
    disciplinaryDeductions: 0,
    approvals: {
      hr: 'مكتمل',
      legal: 'معتمد',
      finance: 'مكتمل',
      gm: 'قيد الانتظار',
      executive: 'قيد الانتظار',
      manager: 'معتمد'
    },
    signatures: {
      hr: 'م.ب - عادل المطيري',
      legal: 'مستشار قانوني - صبري شطا',
      fin: 'د.م - جهاد عبد الهادي',
      employee: ''
    },
    timeline: [
      { date: '2026-05-15', actionAr: 'تم إنشاء صك التسوية واستخلاص الحسبة تلقائياً', actionEn: 'Settlement dossier drafted automatically', user: 'عادل المطيري' },
      { date: '2026-05-18', actionAr: 'تمت المصادقة والمراجعة القانونية للأجر الفردي والمدد', actionEn: 'Legal audit completed', user: 'أ. صبري شطا' },
      { date: '2026-05-20', actionAr: 'تم تدقيق الاقتطاعات والقروض المالية وإخلاء الذمة الدفترية', actionEn: 'Financial deduction ledger updated', user: 'جهاد عبد الهادي' }
    ]
  },
  {
    id: 'EOS-1033',
    settlementNumber: 'SET-2026-1033',
    employeeId: '291040512345',
    employeeName: 'محمد فاروق الشاهين',
    department: 'قسم الإنشاءات وفنيين الكادر النفطي',
    settlementDate: '2026-05-25',
    lastWorkingDay: '2026-05-25',
    joiningDate: '2021-12-25',
    terminationReason: TerminationReasonKuwait.RESIGNATION,
    status: 'UnderFinancialReview',
    basicSalary: 600,
    allowances: 100,
    grossSalary: 700,
    serviceYears: 4,
    serviceMonths: 5,
    serviceDays: 0,
    indemnityAmount: 890.350,
    leaveBalanceAmount: 323.080,
    accruedSalaryAmount: 0,
    noticePeriodAmount: 0,
    otherBonuses: 0,
    loansDeduction: 0,
    absenceDeduction: 80.770,
    otherDeductions: 0,
    netPayable: 1132.660,
    legalArticles: ['المادة 51', 'المادة 53', 'المادة 70'],
    notes: 'تم خصم ٣٠ يوماً من مدة الخدمة لمسار الإجازة منقطعة الراتب غير المدفوعة بناء على لجان الامتثال لشؤون العمل، وتخضع براءته لخصم الغياب (٣ أيام). الحسبة تعادل ٥٠٪ بموجب المادة ٥٣.',
    preparedBy: 'منسق شؤون الأجور - ريعان الخالدي',
    nationality: 'سوري',
    jobTitle: 'فني أول ميكانيكا وهياكل',
    leaveBalanceDays: 12,
    absenceDays: 3,
    socialInsuranceDeduction: 0,
    unpaidLeaveDays: 30,
    disciplinaryDeductions: 0,
    approvals: {
      hr: 'مكتمل',
      legal: 'قيد الانتظار',
      finance: 'قيد الانتظار',
      gm: 'قيد الانتظار',
      manager: 'معتمد'
    },
    signatures: {
      hr: 'م.ب - ريعان الخالدي',
      legal: '',
      fin: '',
      employee: ''
    },
    timeline: [
      { date: '2026-05-18', actionAr: 'تقدم الموظف بطلب استقالة رسمية', actionEn: 'Employee tendered Standard Resignation', user: 'محمد فاروق' },
      { date: '2026-05-22', actionAr: 'تم إخلاء طرف العهد الفنية وتصفية الاستقطاعات', actionEn: 'Physical equipment clearances checked', user: 'ريعان الخالدي' }
    ]
  },
  {
    id: 'EOS-1035',
    settlementNumber: 'SET-2026-1035',
    employeeId: '288031578912',
    employeeName: 'مشاري عبد المحسن المطيري',
    department: 'الشؤون القانونية والاستشارات',
    settlementDate: '2026-05-20',
    lastWorkingDay: '2026-05-20',
    joiningDate: '2016-04-15',
    terminationReason: TerminationReasonKuwait.CONSENSUAL_TERMINATION,
    status: 'Completed',
    basicSalary: 1100,
    allowances: 200,
    grossSalary: 1300,
    serviceYears: 10,
    serviceMonths: 1,
    serviceDays: 5,
    indemnityAmount: 10354.200,
    leaveBalanceAmount: 3000.000,
    accruedSalaryAmount: 0,
    noticePeriodAmount: 0,
    otherBonuses: 0,
    loansDeduction: 0,
    absenceDeduction: 0,
    otherDeductions: 0,
    netPayable: 13354.200,
    legalArticles: ['المادة 51', 'المادة 70'],
    notes: 'تمت التسوية والحوالة المصرفية بنجاح عبر البنك الأهلي المتحد برقم حوالة (CBK-749202)، وتم استلام إبراء الذمة العمالية المطلقة المصدقة والمطبوعة مروّسة وتوقيعها من الطرفين.',
    preparedBy: 'مدير شؤون الموظفين - عادل المطيري',
    nationality: 'كويتي',
    jobTitle: 'مستشار كبار الشركاء',
    leaveBalanceDays: 60,
    absenceDays: 0,
    socialInsuranceDeduction: 0,
    unpaidLeaveDays: 0,
    disciplinaryDeductions: 0,
    approvals: {
      hr: 'مكتمل',
      legal: 'معتمد',
      finance: 'مكتمل',
      gm: 'معتمد',
      executive: 'معتمد',
      manager: 'معتمد'
    },
    signatures: {
      hr: 'م.ب - عادل المطيري',
      legal: 'أ. صبري شطا',
      fin: 'ج.ع - جهاد عبد الهادي',
      gm: 'م.م - مشاري المطيري (مفوض)',
      employee: 'مشاري عبد المحسن - ت.إلكتروني'
    },
    timeline: [
      { date: '2026-05-10', actionAr: 'تم التوافق رضاءً على إنهاء العقد وصياغة اتفاقية ودية', actionEn: 'Consensual separation agreed friendly', user: 'عادل المطيري' },
      { date: '2026-05-12', actionAr: 'تم توثيق المخالصة وبراءة طرف العهد كاملة بدون استقطاع', actionEn: 'Full release and zero-debt certified', user: 'أ. صبري شطا' },
      { date: '2026-05-15', actionAr: 'تأكيد الحوالة البنكية التصفوية بنجاح وإيداع المبلغ', actionEn: 'Treasury executed bank transfer', user: 'جهاد عبد الهادي' },
      { date: '2026-05-20', actionAr: 'إغلاق الملف وإحالته للأرشفة كبراءة ذمة تامة ومحكمة', actionEn: 'File closed and archived legally', user: 'عادل المطيري' }
    ]
  }
];

export const translations: Record<'ar' | 'en', any> = {
  ar: {
    title: "إدارة ومخالصات نهاية الخدمة والتسويات العمالية",
    officeName: "مكتب المحامي صبري شطا للمحاماة والاستشارات القانونية والتحكيم",
    lawComplianceBadge: "مطابق لقانون العمل الكويتي في القطاع الأهلي رقم 6 لسنة 2010",
    complianceVerified: "معتمد قانوناً",
    searchPlaceholder: "البحث باسم الموظف، الرقم المدني، المسمى الوظيفي...",
    newSettlement: "ملف تسوية ومخالصة جديدة",
    classification: "التصنيف والسبب القانوني لإنهاء الخدمة",
    allClassifications: "كافة الأسباب القانونية",
    statusFilter: "تصفية الملفات حسب حالة الاعتماد",
    dossierCount: "ملف تسوية عمالية",
    serviceDuration: "مدة الخدمة الإجمالية للموظف",
    years: "سنوات",
    months: "أشهر",
    days: "أيام",
    netPayable: "صافي المستحقات والتعويضات المعتمدة",
    kwd: "د.ك",
    statutoryCeiling: "الحد الأقصى المكفول قانوناً",
    underLimit: "ضمن النطاق القانوني",
    resignationScale: "نسبة استحقاق مكافأة نهاية الخدمة (المادة 51)",
    firstFiveYears: "الخمس سنوات الأولى",
    beyondFiveYears: "السنوات التالية",
    calculationsTab: "محرك احتساب التسوية",
    documentsTab: "المستندات القانونية والمخالصات",
    approvalsTab: "اعتمادات أطراف العلاقة",
    dependenciesTab: "تصفية العهد والربط المالي",
    basicSalary: "الراتب الأساسي الأخير",
    allowances: "البدلات الثابتة والتعويضات",
    joiningDate: "تاريخ مباشرة العمل الفعلي",
    lastWorkingDay: "تاريخ انتهاء الخدمة (آخر يوم عمل)",
    leaveBalance: "رصيد الإجازات السنوية المستحقة (يوم)",
    absenceDays: "أيام الغياب بدون عذر مقبول (يوم)",
    totalEarnings: "إجمالي المستحقات المالية (+)",
    totalDeductions: "إجمالي الاستقطاعات والخصومات (-)",
    saveDossier: "حفظ ومزامنة ملف التسوية",
    formulasBreakdown: "مسار التدقيق الحسابي التفصيلي للمكافأة",
    dailyWageBasis: "أساس حساب الأجر اليومي (مقسم على 26)",
    dailyRate: "معدل الراتب اليومي النهائي",
    formulaUsed: "المعادلة المطبقة بموجب المادة 51",
    formulaSample: "(الراتب الأساسي + البدلات الثابتة) / 26 = الأجر اليومي",
    mathTransparency: "التفصيل الرياضي لمكافأة نهاية الخدمة (مادة 51)",
    signaturesSec: "مصفوفة التوقيعات والاعتمادات الرسمية لبراءة الذمة",
    employeeSignature: "توقيع الطرف الثاني (الموظف - إقرار الوفاء)",
    hrApproval: "تدقيق واعتماد إدارة الموارد البشرية",
    legalApproval: "المصادقة القانونية لمكتب المحامي صبري شطا",
    financeApproval: "الرقابة وتأكيد التحويل المالي والدفع الإمراري",
    assetsClearance: "تصفية ومقاصة الأصول والعهد العينية المستلمة",
    laptopHandover: "جهاز الحاسب المحمول (اللابتوب) وملحقاته وعهدته",
    badgeHandover: "بطاقة المرور الإلكترونية وبوابة الدخول الذكي",
    keysHandover: "مفاتيح المكاتب والخزائن العينية المخصصة",
    carHandover: "سيارة المنشأة والعهد والآليات اللوجستية",
    returnedStatus: "تم الاسترداد بحالة سليمة ✔",
    pendingStatus: "قيد المراجعة والاستلام المعلق ⏳",
    lostStatus: "مفقود - استقطاع القيمة التقديرية للأصل",
    bankLinkage: "التسوية المصرفية والتحويل البنكي للمستحقات",
    targetBank: "البنك المعتمد بدولة الكويت للإيداع",
    bankReceipt: "رقم الحوالة المصرفية للإيداع المعتمد",
    ibanCode: "رقم الحساب الدولي المبرأ للذمة (IBAN)",
    printDeed: "طباعة صك المخالصة المروّسة",
    exportWord: "تصدير إلى ملف Word",
    lawFirmStationery: "صك مروّس رسمي - مكتب صبري شطا للمحاماة",
    printTitle: "سند المخالصة وإبراء الذمة العمالية المطلقة والتسوية الشاملة",
    phone: "الهاتف: +965 22000000",
    email: "البريد الإلكتروني: info@shatta-law.com",
    address: "العنوان: برج القبلة، شرق، دولة الكويت",
    pageOf: "صفحة 1 من 1",
    verificationAr: "مستند تسوية معتمد ومتوافق مع الهيئة العامة للقوى العاملة وقوانين العمل الكويتية",
    qrLabel: "مسح الرمز للتحقق من مصادقة السند",
    unpaidLeaveDeduction: "استقطاع أيام الغياب والإجازات غير المدفوعة",
    notCertified: "بانتظار المراجعة والتدقيق",
    draft: "مسودة غير معتمدة",
    reviewing: "قيد التدقيق القانوني والمالي",
    certified: "تمت المخالصة وبانتظار الإيداع البنكي",
    approved: "تم إيداع المستحقات مالياً وإغلاق الملف",
    activeDossier: "الملف العمالي النشط المستهدف",
    litigationEscalation: "إحالة الملف إلى شكوى عمالية (إدارة علاقات العمل)"
  },
  en: {
    title: "End of Service & Labor Settlements",
    officeName: "Sabri Shatta Law Firm & Arbitrations",
    lawComplianceBadge: "Compliant with Kuwait Labor Law No. 6 of 2010",
    complianceVerified: "Legally Verified",
    searchPlaceholder: "Search name, civil ID, title...",
    newSettlement: "New Settlement File",
    classification: "Legal Classification",
    allClassifications: "All Classifications",
    statusFilter: "Filter by Status",
    dossierCount: "Labor files",
    serviceDuration: "Total Service Duration",
    years: "Years",
    months: "Months",
    days: "Days",
    netPayable: "Net Approved Paycut",
    kwd: "KWD",
    statutoryCeiling: "Statutory Cap",
    underLimit: "Within Law Range",
    resignationScale: "Resignation Scale (Art. 51)",
    firstFiveYears: "First 5 Years",
    beyondFiveYears: "Beyond 5 Years",
    calculationsTab: "Calculation Engine",
    documentsTab: "Legal Forms",
    approvalsTab: "Sign-offs & Workflow",
    dependenciesTab: "Clearances & Debts",
    basicSalary: "Basic Salary",
    allowances: "Fixed Allowances",
    joiningDate: "Hired Date",
    lastWorkingDay: "Last Working Day",
    leaveBalance: "Unused Leave Days",
    absenceDays: "Unexcused Absence (Days)",
    totalEarnings: "Total Earnings",
    totalDeductions: "Total Deductions",
    saveDossier: "Sync & Update Dossier",
    formulasBreakdown: "Detailed Mathematical Formulas",
    dailyWageBasis: "Daily Wage Basis (26 Days Divisor)",
    dailyRate: "Daily Wage Rate",
    formulaUsed: "Equation applied for Art.51 gr",
    formulaSample: "Basic salary + Allowances / 26 = Daily wage basis",
    mathTransparency: "Math Transparency Audit (Art. 51)",
    signaturesSec: "Waiver & Administrative Signatures Matrix",
    employeeSignature: "Employee Handover Sign (Absolute Release)",
    hrApproval: "HR Specialist Audit & Stamp",
    legalApproval: "Legal Consultation of Sabri Shatta",
    financeApproval: "Audit of Treasury & bank transfer",
    assetsClearance: "Physical Asset & Inventory Clearances",
    laptopHandover: "Corporate Laptop & Devices Handover",
    badgeHandover: "Access Badge & Digital Accounts",
    keysHandover: "Physical Keys & Office Drawer Release",
    carHandover: "Company Fleet car Transfer",
    returnedStatus: "Returned & Safe ✔",
    pendingStatus: "Under Review ⏳",
    lostStatus: "Lost - Offset Value Deducted",
    bankLinkage: "Clearing & Bank Wire Remittances",
    targetBank: "Remitted Kuwait Bank",
    bankReceipt: "Wire Transfer ID Number",
    ibanCode: "Receiver IBAN Number",
    printDeed: "Print Official Document",
    exportWord: "Export to Word",
    lawFirmStationery: "Certified Letterhead of Sabri Shatta Law Firm",
    printTitle: "Receipt of Service Clearances & General Discharge Act",
    phone: "Tel: +965 22000000",
    email: "Email: info@shatta-law.com",
    address: "Address: Al-Qibla Tower, Sharq, Kuwait",
    pageOf: "Page 1 of 1",
    verificationAr: "Digitally certified by Sabri Shatta under the supervision of Kuwait Labor Affairs",
    qrLabel: "Scan to Verify QR",
    unpaidLeaveDeduction: "Absence Deductions",
    notCertified: "Unapproved",
    draft: "Draft",
    reviewing: "Under Review",
    certified: "Discharged",
    approved: "Disbursed",
    activeDossier: "Active Labor Dossier",
    litigationEscalation: "Escalate dossier to Court Case"
  }
};

