import { LocalEmployee, LocalAppraisal } from './PerformanceAppraisalTypes';

export const mockEmployeesList: LocalEmployee[] = [];

export const initialAppraisalsSeed: LocalAppraisal[] = [];

export const translations = {
  ar: {
    title: "منظومة تقييم الأداء والتحليلات الوظيفية",
    subtitle: "قسم تقييم الأداء والبيانات الوظيفية المعتمد - مكتب المحامي صبري شطا للمحاماة",
    firmName: "مكتب المحامي صبري شطا للمحاماة والاستشارات القانونية والتحكيم",
    searchPlaceholder: "ابحث بالاسم، الرقم المدني، المسمى الوظيفي...",
    allDepts: "كافة الإدارات والشبكات",
    allTiers: "كافة مستويات التقييم",
    allStatus: "كافة الحالات",
    excellent: "ممتاز / يتخطى التوقعات",
    veryGood: "جيد جداً / يفوق المتوقع",
    good: "جيد / يلبي التوقعات",
    weak: "ضعيف / يحتاج تطوير",
    draft: "مسودة تقييم",
    pending: "قيد المراجعة والاعتماد",
    certified: "معتمد ومغلق",
    newBtn: "إدخال تقييم جديد",
    sidebarTitle: "تصنيفات الملفات ورقابة الأداء",
    deptSection: "إدارات مكتب صبري شطا",
    tierSection: "نطاقات الدرجات والتقييمات",
    statusSection: "حالة الاعتماد القانوني",
    civilIdLabel: "الرقم المدني الكويتي",
    joiningDateLabel: "تاريخ الالتحاق بالمكتب",
    basicSalaryLabel: "الراتب الأساسي",
    allowancesLabel: "البدلات والعلاوات الكادرية",
    warningsLabel: "السجل التأديبي والإنذارات",
    warningsActive: "إنذار نشط",
    warningsNone: "سجل نظيف بالكامل",
    appraiserLabel: "المقيّم المسؤول",
    scoreLabel: "النتيجة النهائية",
    periodLabel: "فترة التقييم الإداري",
    viewDossier: "معاينة التقرير الرسمي",
    duplicateApp: "تكرار كمسودة",
    deleteApp: "حذف السجل",
    printDeed: "طباعة صك التقييم الرسمي",
    emptyList: "لا توجد سجلات مطابقة حالياً للفحص",
    emptySub: "تأكد من اختيار تصنيفات أخرى أو إضافة ملف تقييم جديد عبر المحرك بالأعلى.",
    
    // Wizard
    wizardTitleAddNew: "محرك إعداد صياغة تقييم أداء جديد",
    wizardTitleEdit: "تعديل تفاصيل تقييم الأداء والمطابقة",
    step1: "١. اختيار ملف العامل والتحقق",
    step2: "٢. جودة الكفاءة والتنافسية",
    step3: "٣. مسارات التمكين والتناص",
    step4: "٤. المصادقة والختم الرقمي",
    selectEmployee: "اختر موظف من سجلات الكادر المعتمدة...",
    autofillAlert: "نمط ذكي: تم جلب المتغيرات، السجل المالي، والعقود والملخصات التأديبية للموظف آلياً بنسبة ١٠0%.",
    kpi1: "جودة الصياغة القانونية والبحث وصياغة العقود",
    kpi1Desc: "مدى متانة المذكرات القانونية، مطابقة أسانيد المدعي، والبحث العميق في أحكام محكمة التمييز الكويتية.",
    kpi2: "نسبة إنجاز القضايا والالتزام بآجال الجلسات",
    kpi2Desc: "معدل كسب الدفوع، تقديم مذكرات الخبراء بالموعد، وتحقيق النتائج الإيجابية للموكلين.",
    kpi3: "التعامل مع الموكلين وأخلاقيات المهنة وشرف السلوك",
    kpi3Desc: "مستوى رضا أطراف النزاع، المحافظة على أسرار الموكلين، والتواصل الدبلوماسي المستمر.",
    kpi4: "الالتزام باللوائح والدوام لوزارة الشؤون",
    kpi4Desc: "ساعات العمل الرسمية، البصمة، تنفيذ القرارات الصادرة عن الإدارة الشريكة والشركاء القضائيين.",
    strengthsLabel: "نقاط القوة الاستشارية والعملية",
    strengthsPlaceholder: "مثال: مهارة استثنائية في إيجاد الثغرات للدعاوى التجارية الكبرى وتحقيق مكاسب مالية...",
    improvementsLabel: "مجالات التطوير المهني المستهدف",
    improvementsPlaceholder: "مثال: يحتاج إلى تعزيز سرعة المرافعة الشفوية أمام الدوائر التجارية المستعجلة...",
    trainingLabel: "الدورات والندوات القضائية الموصى بها",
    trainingPlaceholder: "مثال: دورتين لغة إنجليزية قانونية، ورشة عمل التحكيم الدولي...",
    signeeLabel: "اسم المفوض الموقع (المدير المسؤول)",
    signeePlaceholder: "ادخل اسمك الرباعي للمصادقة الإدارية...",
    actionPlan: "خطة التدخل والتقويم الإجباري",
    actionPlanPlaceholder: "ادخل خطة المتابعة الـ 90 يوماً في حال تدني الأداء...",
    prevBtn: "السابق",
    nextBtn: "التالي",
    saveDraft: "حفظ كمسودة مؤقتة",
    submitCertify: "إعتماد وتصدير صك التقييم النهائي",
    cancel: "إلغاء التغييرات",
    
    // Official Report Letterhead
    repTitle: "صك تقييم الأداء الوظيفي والنزاهة المهنية الكادرية",
    stateOfKuwait: "دولة الكويت",
    adalahSystem: "نظام عدالة المؤتمت",
    legalAuditSec: "إدارة الرقابة والامتثال الداعي",
    referenceId: "الرقم المرجعي والتوثيقي:",
    evaluationDate: "تاريخ الإصدار والطباعة:",
    certifiedTrue: "مستند رسمي معتمد وصادر عن مكتب صبري شطا وخاضع لرقابة الهيئة العامة للقوى العاملة بدولة الكويت.",
    metricsTable: "جدول تحليل درجات الكفاءة التراكمية",
    kpiCol: "معيار الكفاءة واللوائح المهنية المعتمدة",
    scoreCol: "الدرجة المستحقة",
    weightCol: "الوزن النسبي",
    gradeCol: "التقييم الشامل",
    gradeExcellent: "ممتاز جداً - استثنائي",
    gradeVeryGood: "جيد جداً - يفوق المتوقع",
    gradeGood: "جيد - مستوفي الشروط",
    gradeWeak: "ضعيف - يحتاج لتقويم فوري وسريع",
    digitalStampTitle: "الختم المائي والتوقيع اللامركزي الموثق",
    verCode: "رمز التحقق الثنائي الآمن:",
    sigsBlock: "مصفوفة التوقيعات الرسمية المعتمدة للمستند",
    sigManager: "توقيع رئيس القسم / الشريك",
    sigHr: "توقيع رئيس الموارد البشرية",
    sigAttorney: "توقيع المحامي العام المدير",
    printBtn: "طباعة المستند فورياً",
    exportPdf: "تصدير إلى PDF",
    exportWord: "تحميل ملف Word",
    exportExcel: "تصدير كـ Excel لمسؤول الرواتب",
    closeBtn: "إغلاق المعاينة",
    kpiScoreText: "من ٥",
    kwd: "د.ك",
    averageScore: "معدل التقييم",
    periodName: "دورة التقييم",
    successMsg: "تم حفظ تقييم الأداء واعتماد صك الامتثال الوظيفي المالي والمسلكي بنجاح!",
    duplicateMsg: "تم تكرار صك التقييم كمسودة مبرمة جديدة بنجاح في سجلات الأداء.",
    deleteMsg: "تم إتلاف ملف التقييم وحذفه تماماً من قاعدة البيانات بنجاح.",
    analyticsOverview: "نظرة عامة على البيانات والتقييمات"
  },
  en: {
    title: "Performance Appraisal & Analytics Module",
    subtitle: "Certified Employee Performance & Compliance Dashboard - Sabri Shatta Law Firm",
    firmName: "Sabri Shatta Law Firm for Advocacy, Legal Consultations & Arbitration",
    searchPlaceholder: "Search by Employee Name, Civil ID, Position...",
    allDepts: "All Departments & Networks",
    allTiers: "All Performance Tiers",
    allStatus: "All Certification Statuses",
    excellent: "Excellent / Exceeds Expectations",
    veryGood: "Very Good / Fulfills Highly",
    good: "Good / Meets Expectations",
    weak: "Weak / Needs Improvement",
    draft: "Draft Appraisal",
    pending: "Under Legal Review",
    certified: "Certified & Locked",
    newBtn: "New Evaluation Profile",
    sidebarTitle: "Dossier Categories & Audit Control",
    deptSection: "Sabri Shatta Departments",
    tierSection: "Score Brackets & Metrics",
    statusSection: "Legal Certification Status",
    civilIdLabel: "Kuwait Civil ID",
    joiningDateLabel: "Firm Affiliation Date",
    basicSalaryLabel: "Basic Salary",
    allowancesLabel: "Staff Allowances & Bonuses",
    warningsLabel: "Disciplinary Log & Warnings",
    warningsActive: "Active Dispute Warning",
    warningsNone: "Completely Clean Record",
    appraiserLabel: "Assessing Authority",
    scoreLabel: "Overall Score",
    periodLabel: "Appraisal Period",
    viewDossier: "View Official Dossier",
    duplicateApp: "Duplicate as Draft",
    deleteApp: "Delete Record",
    printDeed: "Print Legal Appraisal Deed",
    emptyList: "No matching appraisal dossiers found.",
    emptySub: "Please adjust your filter categories or log a new appraisal using the engine above.",
    
    // Wizard
    wizardTitleAddNew: "Performance Appraisal Intake Wizard",
    wizardTitleEdit: "Modify Appraisal Specifications & Compliance",
    step1: "1. Employee Record Select",
    step2: "2. Core Legal KPIs",
    step3: "3. Expansion & Milestones",
    step4: "4. Endorsement & Stamp",
    selectEmployee: "Select accredited employee from HR records...",
    autofillAlert: "Smart Sync: Basic salary, historical dispute logs, and contract codes loaded at 100%.",
    kpi1: "Legal Drafting & Research Quality",
    kpi1Desc: "Cohesiveness of legal briefs, argument alignments, and deep precedent search in Kuwait Court of Cassation dockets.",
    kpi2: "Case Success Rate & Deadlines Commitment",
    kpi2Desc: "Ratio of successful rulings, prompt submittals to Experts Authority, and client commercial victories.",
    kpi3: "Client Relations & Professional Ethics",
    kpi3Desc: "Client feedback parameters, preservation of case secrets, and high integrity representation practices.",
    kpi4: "Attendance, Punctuality & Regulations Compliance",
    kpi4Desc: "Working log matching Kuwait Ministry of Social Affairs regulations and internal partnership decrees.",
    strengthsLabel: "Inherent Advisory & Strategy Strengths",
    strengthsPlaceholder: "E.g., Exceptional acuity in spotting loopholes within multi-million KWD corporate legal disputes.",
    improvementsLabel: "Professional Development Target Goals",
    improvementsPlaceholder: "E.g., Needs to accelerate verbal oral presentation before urgent commercial arbitration panels.",
    trainingLabel: "Recommended Judicial Courses & Seminars",
    trainingPlaceholder: "E.g., Specialized Corporate Contract English courses, Arbitration Advocacy workshops.",
    signeeLabel: "Authorizing Managing Partner (Signee)",
    signeePlaceholder: "Enter full name for legal digital signature log...",
    actionPlan: "90-Day Corrective Performance Plan",
    actionPlanPlaceholder: "Detail mandatory monitoring procedures for unsatisfactory scores...",
    prevBtn: "Previous",
    nextBtn: "Next",
    saveDraft: "Save as Temp Draft",
    submitCertify: "Authorize & Issue Certified Deed",
    cancel: "Discard Changes",
    
    // Official Report Letterhead
    repTitle: "Official Employee Performance & Integrity Evaluation Deed",
    stateOfKuwait: "State of Kuwait",
    adalahSystem: "ADALAH Unified Legal Tech",
    legalAuditSec: "Compliance & Legal Audit Bureau",
    referenceId: "Document Ref ID:",
    evaluationDate: "Issuance & Print Date:",
    certifiedTrue: "Official authenticated instrument issued by Sabri Shatta law firm, regulated by the Public Authority for Manpower of Kuwait.",
    metricsTable: "Weighted Competency Analysis Matrix",
    kpiCol: "Performance Criterion / Legal Standards",
    scoreCol: "Awarded Mark",
    weightCol: "Relative Weight",
    gradeCol: "Cumulative Score",
    gradeExcellent: "Excellent - Outstanding Caliber",
    gradeVeryGood: "Very Good - Exceeded Requirements",
    gradeGood: "Good - Fulfilled Expectations",
    gradeWeak: "Weak - Immediate Training Action Plan Required",
    digitalStampTitle: "Digital Integrity Seal & SHA-256 Stamp",
    verCode: "Secure Dual Verification Code:",
    sigsBlock: "Accredited Verification Signature Blocks",
    sigManager: "Managing Partner Signature",
    sigHr: "Director of HR Endorsement",
    sigAttorney: "Managing Attorney Seal",
    printBtn: "Direct Print Deed",
    exportPdf: "Export to Adobe PDF",
    exportWord: "Download MS Word (.docx)",
    exportExcel: "Export Excel for Payroll",
    closeBtn: "Close Document Screen",
    kpiScoreText: "out of 5",
    kwd: "KWD",
    averageScore: "Average Grade",
    periodName: "Appraisal Term",
    successMsg: "Appraisal dossier saved and the certified legal performance deed issued successfully!",
    duplicateMsg: "The performance profile has been duplicated as a new draft in the platform registry.",
    deleteMsg: "Performance appraisal dossier dismantled and completely purged from records.",
    analyticsOverview: "Performance Analytics Overview"
  }
};
