import { LocalEmployee, LocalAppraisal } from './PerformanceAppraisalTypes';

export const mockEmployeesList: LocalEmployee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP-KS-501',
    civilId: '298061201534',
    fullName: { ar: 'أحمد محمود العبدالله', en: 'Ahmed Mahmoud Al-Abdullah' },
    jobTitle: { ar: 'مستشار قانوني أول - شركات', en: 'Senior Legal Corporate Advisor' },
    department: { ar: 'الشؤون التجارية والشركات', en: 'Corporate & Commercial' },
    joiningDate: '2020-03-15',
    basicSalary: 1800,
    allowancesAmount: 450,
    nationality: { ar: 'كويتي', en: 'Kuwaiti' },
    warningsCount: 0,
    avatarInitials: 'AA',
    hireDate: '2020-03-15'
  },
  {
    id: 'emp-2',
    employeeId: 'EMP-KS-502',
    civilId: '293021102941',
    fullName: { ar: 'سحر جاسم الفيلي', en: 'Sahar Jassem Al-Fayli' },
    jobTitle: { ar: 'باحث جنائي ومحامي مرافعة', en: 'Criminal Defense Litigation Attorney' },
    department: { ar: 'القانون العام والجنائي', en: 'Criminal & Public Law' },
    joiningDate: '2022-09-01',
    basicSalary: 1200,
    allowancesAmount: 300,
    nationality: { ar: 'كويتية', en: 'Kuwaiti' },
    warningsCount: 1,
    avatarInitials: 'SF',
    hireDate: '2022-09-01'
  },
  {
    id: 'emp-3',
    employeeId: 'EMP-KS-503',
    civilId: '296052403198',
    fullName: { ar: 'خالد عبدالمحسن الصايغ', en: 'Khaled Abdulmohsen Al-Sayegh' },
    jobTitle: { ar: 'محكم تجاري ومصادق صكوك', en: 'Commercial Arbitrator & Deed Certifier' },
    department: { ar: 'التحكيم والوساطة القضائية', en: 'Arbitration' },
    joiningDate: '2021-05-18',
    basicSalary: 1650,
    allowancesAmount: 400,
    nationality: { ar: 'كويتي', en: 'Kuwaiti' },
    warningsCount: 0,
    avatarInitials: 'KS',
    hireDate: '2021-05-18'
  },
  {
    id: 'emp-4',
    employeeId: 'EMP-KS-504',
    civilId: '291040801249',
    fullName: { ar: 'بدر فهد المطيري', en: 'Bader Fahad Al-Mutairi' },
    jobTitle: { ar: 'مساعد باحث صياغة لوائح', en: 'Junior Legal Research & Brief Associate' },
    department: { ar: 'الشؤون القانونية', en: 'Legal Affairs' },
    joiningDate: '2023-01-15',
    basicSalary: 950,
    allowancesAmount: 155,
    nationality: { ar: 'كويتي', en: 'Kuwaiti' },
    warningsCount: 2,
    avatarInitials: 'BM',
    hireDate: '2023-01-15'
  },
  {
    id: 'emp-5',
    employeeId: 'EMP-KS-505',
    civilId: '295091204851',
    fullName: { ar: 'سارة خالد الصباح', en: 'Sara Khalid Al-Sabah' },
    jobTitle: { ar: 'شريك أول - مستشار استثمار رئيسي', en: 'Senior Partner - Lead Investment Counsel' },
    department: { ar: 'الشؤون التجارية والشركات', en: 'Corporate & Commercial' },
    joiningDate: '2018-02-10',
    basicSalary: 2500,
    allowancesAmount: 600,
    nationality: { ar: 'كويتية', en: 'Kuwaiti' },
    warningsCount: 0,
    avatarInitials: 'SS',
    hireDate: '2018-02-10'
  }
];

export const initialAppraisalsSeed: LocalAppraisal[] = [
  {
    id: 'app-1',
    employeeId: 'emp-1',
    appraisalPeriod: 'Annual 2025',
    appraisalDate: '2025-12-15',
    status: 'Certified',
    appraiserName: { ar: 'أ. صبري شطا', en: 'Sabri Shatta, Esq.' },
    overallScore: 4.88,
    scores: {
      drafting: 5,
      successRate: 4.8,
      clientRelations: 5,
      compliance: 4.7
    },
    strengths: { 
      ar: 'قدرة فذة في تفكيك المذكرات المنافسة وتطوير دفوع دستورية وقانونية بالغة التماسك.', 
      en: 'Incredible ability to dismantle adversary briefs and develop highly cohesive constitutional defenses.' 
    },
    improvements: { 
      ar: 'تحتاج إلى التوسع في تولي إدارة الجلسات كشريك متحدث في المؤتمرات الدولية.', 
      en: 'Needs to expand further as a lead speaker in international arbitration conventions.' 
    },
    training: { 
      ar: 'ندوة صياغة عقود الاستحواذ الكبرى بالتعاون مع نقابة المحامين البريطانية.', 
      en: 'Mega Acquisitions Contracting seminar in collaboration with the British Bar Association.' 
    },
    refId: 'QA-PERF-2025-098',
    signatureCode: 'ae89d1b2f5_shatta_firm_certified',
    signeeName: { ar: 'صبري شطا', en: 'Sabri Shatta' },
    signedAt: '2025-12-16'
  },
  {
    id: 'app-2',
    employeeId: 'emp-2',
    appraisalPeriod: 'Q1 2026',
    appraisalDate: '2026-05-10',
    status: 'Pending Legal/HR Approval',
    appraiserName: { ar: 'د. يوسف شطا', en: 'Dr. Yousef Shatta' },
    overallScore: 4.15,
    scores: {
      drafting: 4.2,
      successRate: 4.5,
      clientRelations: 4,
      compliance: 3.9
    },
    strengths: { 
      ar: 'امتياز في المرافعة وارتجال الحجج القانونية الصلبة أمام محكمة الجنايات.', 
      en: 'Excellent skills in court trial advocacy and improvising solid arguments before criminal circuits.' 
    },
    improvements: { 
      ar: 'يُنصح بالتدقيق الإضافي للأسانيد لتقليل أوقات المراجعة الموازية.', 
      en: 'Recommended to perform extra legal proofing to optimize parallel review timelines.' 
    },
    training: { 
      ar: 'ورشة عمل الدفوع الجنائية والمسؤولية التقصيرية بدولة الكويت.', 
      en: 'Criminal Pleadings & Tort Liability workshop in Kuwait.' 
    },
    refId: 'QA-PERF-2026-012',
    signatureCode: 'c3f290d4e1_shatta_firm_pending',
    signeeName: { ar: 'يوسف شطا', en: 'Yousef Shatta' },
    signedAt: '2026-05-11'
  },
  {
    id: 'app-3',
    employeeId: 'emp-4',
    appraisalPeriod: 'Annual 2025',
    appraisalDate: '2025-12-20',
    status: 'Draft',
    appraiserName: { ar: 'أ. فواز الصباح', en: 'Fawaz Al-Sabah' },
    overallScore: 2.85,
    scores: {
      drafting: 3.0,
      successRate: 2.5,
      clientRelations: 3.0,
      compliance: 2.9
    },
    strengths: { 
      ar: 'يظهر التزاماً بالعمل الإداري المساعد وترتيب ملفات القضايا بالشؤون القانونية.', 
      en: 'Shows good dedication to administrative assistance and filing case materials correctly.' 
    },
    improvements: { 
      ar: 'يحتاج إلى تنمية مهارة صياغة لوائح الدعاوى والالتزام بساعات البصمة الرسمية.', 
      en: 'Needs immediate training in draft pleading briefs and committing to official biometric sign-in.' 
    },
    training: { 
      ar: 'علاج إجباري في الصياغة الإدارية وقواعد مراجعة الخبراء المبتدئة.', 
      en: 'Mandatory remedial training on administrative drafting & junior compliance methodologies.' 
    },
    refId: 'QA-PERF-2025-105',
    signatureCode: 'draft_tempo_no_stamp_992a',
    signeeName: { ar: 'فواز الصباح', en: 'Fawaz Al-Sabah' },
    signedAt: '2025-12-21'
  }
];

export const translations = {
  ar: {
    title: "منظومة تقييم الأداء والتحليلات الوظيفية",
    subtitle: "قسم تقييم الأداء والبيانات الوظيفية المعتمد - مكتب المحامي صبري شطا للمحاماة",
    firmName: "مكتب المحامي صبري شطا للمحاماة والاستشارات القانونية والتحكيم",
    searchPlaceholder: "ابحث بالاسم، الرقم المدني، المسمى الوظيفي...",
    allDepts: "كافة الإدارات والشبكات",
    allTiers: "كافة مستويات التقييم",
    allStatus: "كافة الحالات",
    excellent: "ممتاز / يتخطى التوقعات",
    veryGood: "جيد جداً / يفوق المتوقع",
    good: "جيد / يلبي التوقعات",
    weak: "ضعيف / يحتاج تطوير",
    draft: "مسودة تقييم",
    pending: "قيد المراجعة والاعتماد",
    certified: "معتمد ومغلق",
    newBtn: "إدخال تقييم جديد",
    sidebarTitle: "تصنيفات الملفات ورقابة الأداء",
    deptSection: "إدارات مكتب صبري شطا",
    tierSection: "نطاقات الدرجات والتقييمات",
    statusSection: "حالة الاعتماد القانوني",
    civilIdLabel: "الرقم المدني الكويتي",
    joiningDateLabel: "تاريخ الالتحاق بالمكتب",
    basicSalaryLabel: "الراتب الأساسي",
    allowancesLabel: "البدلات والعلاوات الكادرية",
    warningsLabel: "السجل التأديبي والإنذارات",
    warningsActive: "إنذار نشط",
    warningsNone: "سجل نظيف بالكامل",
    appraiserLabel: "المقيّم المسؤول",
    scoreLabel: "النتيجة النهائية",
    periodLabel: "فترة التقييم الإداري",
    viewDossier: "معاينة التقرير الرسمي",
    duplicateApp: "تكرار كمسودة",
    deleteApp: "حذف السجل",
    printDeed: "طباعة صك التقييم الرسمي",
    emptyList: "لا توجد سجلات مطابقة حالياً للفحص",
    emptySub: "تأكد من اختيار تصنيفات أخرى أو إضافة ملف تقييم جديد عبر المحرك بالأعلى.",
    
    // Wizard
    wizardTitleAddNew: "محرك إعداد صياغة تقييم أداء جديد",
    wizardTitleEdit: "تعديل تفاصيل تقييم الأداء والمطابقة",
    step1: "١. اختيار ملف العامل والتحقق",
    step2: "٢. جودة الكفاءة والتنافسية",
    step3: "٣. مسارات التمكين والتناص",
    step4: "٤. المصادقة والختم الرقمي",
    selectEmployee: "اختر موظف من سجلات الكادر المعتمدة...",
    autofillAlert: "نمط ذكي: تم جلب المتغيرات، السجل المالي، والعقود والملخصات التأديبية للموظف آلياً بنسبة ١٠0%.",
    kpi1: "جودة الصياغة القانونية والبحث وصياغة العقود",
    kpi1Desc: "مدى متانة المذكرات القانونية، مطابقة أسانيد المدعي، والبحث العميق في أحكام محكمة التمييز الكويتية.",
    kpi2: "نسبة إنجاز القضايا والالتزام بآجال الجلسات",
    kpi2Desc: "معدل كسب الدفوع، تقديم مذكرات الخبراء بالموعد، وتحقيق النتائج الإيجابية للموكلين.",
    kpi3: "التعامل مع الموكلين وأخلاقيات المهنة وشرف السلوك",
    kpi3Desc: "مستوى رضا أطراف النزاع، المحافظة على أسرار الموكلين، والتواصل الدبلوماسي المستمر.",
    kpi4: "الالتزام باللوائح والدوام لوزارة الشؤون",
    kpi4Desc: "ساعات العمل الرسمية، البصمة، تنفيذ القرارات الصادرة عن الإدارة الشريكة والشركاء القضائيين.",
    strengthsLabel: "نقاط القوة الاستشارية والعملية",
    strengthsPlaceholder: "مثال: مهارة استثنائية في إيجاد الثغرات للدعاوى التجارية الكبرى وتحقيق مكاسب مالية...",
    improvementsLabel: "مجالات التطوير المهني المستهدف",
    improvementsPlaceholder: "مثال: يحتاج إلى تعزيز سرعة المرافعة الشفوية أمام الدوائر التجارية المستعجلة...",
    trainingLabel: "الدورات والندوات القضائية الموصى بها",
    trainingPlaceholder: "مثال: دورتين لغة إنجليزية قانونية، ورشة عمل التحكيم الدولي...",
    signeeLabel: "اسم المفوض الموقع (المدير المسؤول)",
    signeePlaceholder: "ادخل اسمك الرباعي للمصادقة الإدارية...",
    actionPlan: "خطة التدخل والتقويم الإجباري",
    actionPlanPlaceholder: "ادخل خطة المتابعة الـ 90 يوماً في حال تدني الأداء...",
    prevBtn: "السابق",
    nextBtn: "التالي",
    saveDraft: "حفظ كمسودة مؤقتة",
    submitCertify: "إعتماد وتصدير صك التقييم النهائي",
    cancel: "إلغاء التغييرات",
    
    // Official Report Letterhead
    repTitle: "صك تقييم الأداء الوظيفي والنزاهة المهنية الكادرية",
    stateOfKuwait: "دولة الكويت",
    adalahSystem: "نظام عدالة المؤتمت",
    legalAuditSec: "إدارة الرقابة والامتثال الداعي",
    referenceId: "الرقم المرجعي والتوثيقي:",
    evaluationDate: "تاريخ الإصدار والطباعة:",
    certifiedTrue: "مستند رسمي معتمد وصادر عن مكتب صبري شطا وخاضع لرقابة الهيئة العامة للقوى العاملة بدولة الكويت.",
    metricsTable: "جدول تحليل درجات الكفاءة التراكمية",
    kpiCol: "معيار الكفاءة واللوائح المهنية المعتمدة",
    scoreCol: "الدرجة المستحقة",
    weightCol: "الوزن النسبي",
    gradeCol: "التقييم الشامل",
    gradeExcellent: "ممتاز جداً - استثنائي",
    gradeVeryGood: "جيد جداً - يفوق المتوقع",
    gradeGood: "جيد - مستوفي الشروط",
    gradeWeak: "ضعيف - يحتاج لتقويم فوري وسريع",
    digitalStampTitle: "الختم المائي والتوقيع اللامركزي الموثق",
    verCode: "رمز التحقق الثنائي الآمن:",
    sigsBlock: "مصفوفة التوقيعات الرسمية المعتمدة للمستند",
    sigManager: "توقيع رئيس القسم / الشريك",
    sigHr: "توقيع رئيس الموارد البشرية",
    sigAttorney: "توقيع المحامي العام المدير",
    printBtn: "طباعة المستند فورياً",
    exportPdf: "تصدير إلى PDF",
    exportWord: "تحميل ملف Word",
    exportExcel: "تصدير كـ Excel لمسؤول الرواتب",
    closeBtn: "إغلاق المعاينة",
    kpiScoreText: "من ٥",
    kwd: "د.ك",
    averageScore: "معدل التقييم",
    periodName: "دورة التقييم",
    successMsg: "تم حفظ تقييم الأداء واعتماد صك الامتثال الوظيفي المالي والمسلكي بنجاح!",
    duplicateMsg: "تم تكرار صك التقييم كمسودة مبرمة جديدة بنجاح في سجلات الأداء.",
    deleteMsg: "تم إتلاف ملف التقييم وحذفه تماماً من قاعدة البيانات بنجاح.",
    analyticsOverview: "نظرة عامة على البيانات والتقييمات"
  },
  en: {
    title: "Performance Appraisal & Analytics Module",
    subtitle: "Certified Employee Performance & Compliance Dashboard - Sabri Shatta Law Firm",
    firmName: "Sabri Shatta Law Firm for Advocacy, Legal Consultations & Arbitration",
    searchPlaceholder: "Search by Employee Name, Civil ID, Position...",
    allDepts: "All Departments & Networks",
    allTiers: "All Performance Tiers",
    allStatus: "All Certification Statuses",
    excellent: "Excellent / Exceeds Expectations",
    veryGood: "Very Good / Fulfills Highly",
    good: "Good / Meets Expectations",
    weak: "Weak / Needs Improvement",
    draft: "Draft Appraisal",
    pending: "Under Legal Review",
    certified: "Certified & Locked",
    newBtn: "New Evaluation Profile",
    sidebarTitle: "Dossier Categories & Audit Control",
    deptSection: "Sabri Shatta Departments",
    tierSection: "Score Brackets & Metrics",
    statusSection: "Legal Certification Status",
    civilIdLabel: "Kuwait Civil ID",
    joiningDateLabel: "Firm Affiliation Date",
    basicSalaryLabel: "Basic Salary",
    allowancesLabel: "Staff Allowances & Bonuses",
    warningsLabel: "Disciplinary Log & Warnings",
    warningsActive: "Active Dispute Warning",
    warningsNone: "Completely Clean Record",
    appraiserLabel: "Assessing Authority",
    scoreLabel: "Overall Score",
    periodLabel: "Appraisal Period",
    viewDossier: "View Official Dossier",
    duplicateApp: "Duplicate as Draft",
    deleteApp: "Delete Record",
    printDeed: "Print Legal Appraisal Deed",
    emptyList: "No matching appraisal dossiers found.",
    emptySub: "Please adjust your filter categories or log a new appraisal using the engine above.",
    
    // Wizard
    wizardTitleAddNew: "Performance Appraisal Intake Wizard",
    wizardTitleEdit: "Modify Appraisal Specifications & Compliance",
    step1: "1. Employee Record Select",
    step2: "2. Core Legal KPIs",
    step3: "3. Expansion & Milestones",
    step4: "4. Endorsement & Stamp",
    selectEmployee: "Select accredited employee from HR records...",
    autofillAlert: "Smart Sync: Basic salary, historical dispute logs, and contract codes loaded at 100%.",
    kpi1: "Legal Drafting & Research Quality",
    kpi1Desc: "Cohesiveness of legal briefs, argument alignments, and deep precedent search in Kuwait Court of Cassation dockets.",
    kpi2: "Case Success Rate & Deadlines Commitment",
    kpi2Desc: "Ratio of successful rulings, prompt submittals to Experts Authority, and client commercial victories.",
    kpi3: "Client Relations & Professional Ethics",
    kpi3Desc: "Client feedback parameters, preservation of case secrets, and high integrity representation practices.",
    kpi4: "Attendance, Punctuality & Regulations Compliance",
    kpi4Desc: "Working log matching Kuwait Ministry of Social Affairs regulations and internal partnership decrees.",
    strengthsLabel: "Inherent Advisory & Strategy Strengths",
    strengthsPlaceholder: "E.g., Exceptional acuity in spotting loopholes within multi-million KWD corporate legal disputes.",
    improvementsLabel: "Professional Development Target Goals",
    improvementsPlaceholder: "E.g., Needs to accelerate verbal oral presentation before urgent commercial arbitration panels.",
    trainingLabel: "Recommended Judicial Courses & Seminars",
    trainingPlaceholder: "E.g., Specialized Corporate Contract English courses, Arbitration Advocacy workshops.",
    signeeLabel: "Authorizing Managing Partner (Signee)",
    signeePlaceholder: "Enter full name for legal digital signature log...",
    actionPlan: "90-Day Corrective Performance Plan",
    actionPlanPlaceholder: "Detail mandatory monitoring procedures for unsatisfactory scores...",
    prevBtn: "Previous",
    nextBtn: "Next",
    saveDraft: "Save as Temp Draft",
    submitCertify: "Authorize & Issue Certified Deed",
    cancel: "Discard Changes",
    
    // Official Report Letterhead
    repTitle: "Official Employee Performance & Integrity Evaluation Deed",
    stateOfKuwait: "State of Kuwait",
    adalahSystem: "ADALAH Unified Legal Tech",
    legalAuditSec: "Compliance & Legal Audit Bureau",
    referenceId: "Document Ref ID:",
    evaluationDate: "Issuance & Print Date:",
    certifiedTrue: "Official authenticated instrument issued by Sabri Shatta law firm, regulated by the Public Authority for Manpower of Kuwait.",
    metricsTable: "Weighted Competency Analysis Matrix",
    kpiCol: "Performance Criterion / Legal Standards",
    scoreCol: "Awarded Mark",
    weightCol: "Relative Weight",
    gradeCol: "Cumulative Score",
    gradeExcellent: "Excellent - Outstanding Caliber",
    gradeVeryGood: "Very Good - Exceeded Requirements",
    gradeGood: "Good - Fulfilled Expectations",
    gradeWeak: "Weak - Immediate Training Action Plan Required",
    digitalStampTitle: "Digital Integrity Seal & SHA-256 Stamp",
    verCode: "Secure Dual Verification Code:",
    sigsBlock: "Accredited Verification Signature Blocks",
    sigManager: "Managing Partner Signature",
    sigHr: "Director of HR Endorsement",
    sigAttorney: "Managing Attorney Seal",
    printBtn: "Direct Print Deed",
    exportPdf: "Export to Adobe PDF",
    exportWord: "Download MS Word (.docx)",
    exportExcel: "Export Excel for Payroll",
    closeBtn: "Close Document Screen",
    kpiScoreText: "out of 5",
    kwd: "KWD",
    averageScore: "Average Grade",
    periodName: "Appraisal Term",
    successMsg: "Appraisal dossier saved and the certified legal performance deed issued successfully!",
    duplicateMsg: "The performance profile has been duplicated as a new draft in the platform registry.",
    deleteMsg: "Performance appraisal dossier dismantled and completely purged from records.",
    analyticsOverview: "Performance Analytics Overview"
  }
};
